# Python review

Shrt review about some core concepts in Python exemplified by objects in the Numpy library.
Goals: 

- recall basic Python vocab
- practice markdown syntax

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files

**NumPy:** 

- core library for numberical computing in Python
- many of libraries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Let's import NumPy with its **standard abbreviation** np:

In [1]:
import numpy as np

## Variables

**variables:** a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to variable a
a = np.array([[1, 1, 2], [3, 5, 8]])

To view a variables value from our Jupyter notebook:

In [3]:
# Run a cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: use `snake_case` for naming variables.

This is teh convention we will use in the course. why?
`my_variable` or `MyVariable` or `myVariable`, PEP 8 - style guide for python code recommends snake_case

** Remeber that variable names should be both descriptive and concise**

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific. 

Example:

Object: data frame
Properties: number of rows, number of columns, and date created
Actions: selecting a specific row or adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use the word variable and object interchangeably.

## Types

Every object in Python has a **type**, the type tells us what kind of object we have. 
We can also call type of an object the class. 

In [5]:
print(a)

[[1 1 2]
 [3 5 8]]


In [6]:
# See the type/class of a variable/object by using `type` function
type(a)

numpy.ndarray

The numpy.ndarray is the core object/data type of the NumPy package.

In [9]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

`numpy.int64` is not the standard Python integer type `int`

`numpy.int64` is a special date type in Numpy telling us that 1 is an integer stored as a 64-bit number.

Check in: access the value 5 in array `a`:

In [13]:
a[1,1]

5

## Functions

`print` was our first example of a Python **function**

Functions take in a set of **arguments**, separated by commas, and use those arguments to create an **output**.

In the course, we'll be using argument and parameter interchangeably. But they do have slightly different meanings.

We can ask for info about what a function does by executing ? followed by the function name:

In [14]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we obtain is a **docstring**, a special type of comment that is used to document how a function (or a class, or module) works.

Notice is that there are different types of arguments inside the function's parenthesis.

Roughly speaking, a function has two types of arguments:

- **non-optional arguments:** arguements *you* have to specify for the function to work.
- **optional arguments:** arguments that are pre-fulled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value`

Example

`end` is a parameter in `print` with default value a new line
We can pass the value `:-)` to this parameter so that it finished the line with `:-)` instead:

In [15]:
print('Change the end parameter', end = ':-)')

Change the end parameter:-)

## Attributes and methods

An object in Python has attributes and methods. 

- **attribute**: a property of the object, some piece of information about it.
- **method**: a procedure associated with an object, so it is an action where the main ingredient is the object itself.

## Check-in

Make a diagram like the cat one, for a class `fish`. What are its attributes and methods?
- attribute: cartilaginous, color, size
- method: swim, splash, eat

Example:

NumPy arrays have many methds and attributes. For example:

In [16]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [17]:
# T is an example of an attribute, it returns the transpose of array
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [18]:
type(a.T)

numpy.ndarray

In [20]:
# shape another attribute tells us the shape of the array
print(a.shape)
print(type(a.shape))

(2, 3)
<class 'tuple'>


In [22]:
# ndim is an attrivute hold the number of array dimensions
print('dim:', a.ndim, '| type', type(a.ndim))

dim: 2 | type <class 'int'>


Attributes can have many different data types. 

Some examples of methods:

In [23]:
# The min method returns the minimum value in the array along a specified axis.
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

In [24]:
# Run min method without axis
a.min()

1

In [25]:
# method tolist() transform array into a list
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [27]:
type(a.tolist)

builtin_function_or_method

## Exercise

1. Read the print function `help`. What is the type of the argument `sep`? Is this a default or non-default argument? why?
2. Create two new variables, one with the integer value 77 and another with the strong 99.
3. Use your variables to print 77%99%77 by change the value of one of the default arguments in `print`.

In [33]:
# 1. is optional bc it fills in with a blank
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [34]:
#2. 
a = 77
b = "99"

In [37]:
#3. 
print(a, b, a, sep = '%')

77%99%77
